services:
  api:
    build: .
    container_name: bookmark_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}
      - DEBUG=${DEBUG}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
