services:
  api:
    build: .
    container_name: user_engagement_api
    ports:
      - "8010:8010"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}
      - DEBUG=${DEBUG}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - .:/app
    restart: always

  tests:
    build: .
    container_name: user_engagement_tests
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}
      - DEBUG=${DEBUG}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - .:/app
    command: [ "pytest", "-v", "--disable-warnings" ]
    restart: "no"

  user_engagement_db:
    image: mongo:6
    container_name: user_engagement_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
